### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by marcolarosa** [describo/crate-builder-component-react#20]
HI @beepsoft  - please build a new react component when you can.

The crate component has had a bit of work done to it:
https://github.com/describo/crate-builder-component/releases/tag/v0.49.4
https://github.com/describo/crate-builder-component/releases/tag/v0.48.0
https://github.com/describo/crate-builder-component/releases/tag/v0.47.0

**Comment by beepsoft** [comment]
New release is based on 0.53.0 https://github.com/describo/crate-builder-component-react/releases/tag/0.53.0
