### ISSUE TITLE
Update to 0.66.0

### ISSUE THREAD

**Issue by marcolarosa** [describo/crate-builder-component-react#21]
@beepsoft Can you please check that nothing has changed for you in react with the latest release? I've stopped assuming that all of fontawesome has been imported and the component now uses targeted imports with the vue-fontawesome component.

So - you should be able to remove the global fontawesome import from your component to.

https://github.com/describo/crate-builder-component/releases/tag/v0.66.0

**Comment by marcolarosa** [comment]
https://github.com/describo/crate-builder-component-react/blob/main/src/DescriboCrateBuilder.tsx#L13-L15

should no longer be needed

**Comment by beepsoft** [comment]
Thanks, I will check it!
