### ISSUE TITLE
Update to 0.69.1

### ISSUE THREAD

**Issue by marcolarosa** [describo/crate-builder-component-react#22]
https://github.com/describo/crate-builder-component/releases/tag/v0.69.0
https://github.com/describo/crate-builder-component/releases/tag/v0.69.1

This adds a new component configuration option `enableEntityTimestamps` which manages created / modified timestamps on entities like a DB would do. It's disabled by default.

**Comment by beepsoft** [comment]
Published 0.69.1 

https://www.npmjs.com/package/@describo/crate-builder-component-react
